### ISSUE TITLE
add grafana geokrety config

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-ansible#2]
In order to integrate geokrety/geokrety-website#300 we need to provide a grafana config files wich embeds existing dashboards and datasources

A working docker-compose file already exists for gkShell :

compose file: [docker-compose.yml](https://github.com/geokrety/geokrety-website/blob/71e50315a3bee991e458c03cdc58adbd0f5fe9c7/gkShell/docker-compose.yml#L50)
resources: [grafana/](https://github.com/geokrety/geokrety-website/tree/feature/metrics/gkShell/config/grafana)

**Comment by kumy** [comment]
It's over there: https://github.com/geokrety/geokrety-grafana/tree/main/files/conf/provisioning ;)
